apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: registry.cn-hangzhou.aliyuncs.com/zhouhaorui/blog_event_bus
          ports:
            - containerPort: 4005
      imagePullSecrets:
        - name: eventbussecret
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-serv
spec:
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005
