apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: registry.cn-hangzhou.aliyuncs.com/zhouhaorui/blog_project
      imagePullSecrets:
        - name: alisecret
