apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: registry.cn-hangzhou.aliyuncs.com/zhouhaorui/blog_project
          ports:
            - containerPort: 4000
      imagePullSecrets:
        - name: alisecret
---
apiVersion: v1
kind: Service
metadata:
  name: posts-node-deploy
spec:
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
