apiVersion: v1
kind: Service
metadata:
  name: post-serv
spec:
  type: NodePort
  # select a specific pod
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 31553
